### ISSUE TITLE
Pig Latin Specs Not Consistent

### ISSUE THREAD

**Issue by genericlady** [learn-co-curriculum/sinatra-mvc-lab#12]
### ./spec/sinatra_mvc_lab_spec.rb:41

_Once_ is expected to be _eOncay_

So if it ends with a vowel and we are expected to move it to the beginning and then add 'ay' the same should be expected for 
### ./spec/sinatra_mvc_lab_spec.rb:57

_alone_ is expected to become _aloneay_

However this is not consistent with the expectation written at line 41.  _alone_ and _once_ both begin and end with vowels.  so far as I can see if you want to keep _eOncay_ the same then _aloneay_ should be _ealonay_.  

If you want to keep _alone_ as _aloneay_ then _eOncay_ needs to be _Onceay_ since it ends with a vowel.

**Comment by AnnJohn** [comment]
@ruchiramani based on the PR you merged from yesterday, can you see if this issue can be closed? thanks

**Comment by ruchiramani** [comment]
@AnnJohn According to the PR i merged, the rules were defined differently and the specs were accordingly to them and not this way. I'm going to close this issue as we have changed the the description which go with these specs.
