### ISSUE TITLE
piglatinizer_spec.rb

### ISSUE THREAD

**Issue by Richard-Frost** [learn-co-curriculum/sinatra-mvc-lab#13]
Hello I believe there is an error in piglatinizer_spec.rb.  The error I am getting is that it wants I to equal "Iway" but I think it should be Iyay?

it 'piglatinizes an individual word' do 

```
expect(words.piglatinize("I")).to eq("Iway")
```

**Comment by Richard-Frost** [comment]
just an fyi... the solutuon in this lab doesn't pass.  I realize the
original issue I raised want fully correct.

**Comment by antoinfive** [comment]
@Richard-Frost Thank you for raising this issue, however, the lab spec is correct as it stands. 
https://en.wikipedia.org/wiki/Pig_Latin
