### ISSUE TITLE
Submit button needs to have value="submit"

### ISSUE THREAD

**Issue by mdo5004** [learn-co-curriculum/sinatra-mvc-lab#15]
Using `<input type="submit">` or even `<input type="submit" name="submit">` does not work in Capybara. Instructions should probably include that `<input>` needs `value = "submit"` to work.

**Comment by DanielSeehausen** [comment]
Thank you for spotting this issue and providing feedback @mdo5004 
@maxwellbenton has added content to earlier material in the curriculum to address just this! Thank you for bringing it to our attention. 

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
