### ISSUE TITLE
Solution code does not pass test

### ISSUE THREAD

**Issue by TylerNodell** [learn-co-curriculum/sinatra-mvc-lab#25]
When attempting to figure out why my code was not passing tests I check against the solutions only to find that the solutions do not pass the tests either.

**Comment by drakeltheryuujin** [comment]
Hi @TylerNodell,

The solution branch passes all tests.

Please read this [Learn Help Center](http://help.learn.co/) article. 

If you still require assistance after reading the Help Center article, pop into [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ), where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-suapport/does-my-program-or-course-have-technical-coach-support)) and fellow community members can provide additional help. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

If, after consulting the Help Center and AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
