### ISSUE TITLE
Capitalization Q's in the Specs

### ISSUE THREAD

**Issue by Peter-G-Stone** [learn-co-curriculum/sinatra-mvc-lab#26]
--- there seems to be some irregularities in terms of what the tests expect for capitalization. I set it up to pass, but it seems to be needlessly complicated and unrelated to the subject at hand. good practice for handling edge cases I guess.. Just something to think about.

**Comment by sgharms** [comment]
I was unable to reproduce this. I implemented this afresh, using the rules on Wikipedia and was able to produce the correct solution. Looking at your implementation, you might want to add capital letters to `VOWELS`. Much of your logic would be simplified by doing so.

**Comment by Peter-G-Stone** [comment]
Thanks for the feedback! Much appreciation.
