### ISSUE TITLE
not universally familiar

### ISSUE THREAD

**Issue by d-d-d-dalia** [learn-co-curriculum/sinatra-mvc-lab#27]
I've worked with a few international students, in particular, for whom pig latin is completely foreign.

**Comment by drakeltheryuujin** [comment]
Hi @d-d-d-dalia,

Thank you for spotting this issue and providing feedback.
We have updated the materials and believe the issue has been resolved.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
