### ISSUE TITLE
Re #28: "ayStream" should be "eamStray" unless I'm missing something

### ISSUE THREAD

**Issue by DakotaLMartinez** [learn-co-curriculum/sinatra-mvc-lab#29]
@drakeltheryuujin The update to the specs doesn't seem to make sense here. "Stream" should be "eamStray" not "ayStream" unless I'm missing something. Can we revert that commit making the change?

**Comment by emilywilder** [comment]
Thanks for the issue @DakotaLMartinez. According to https://web.ics.purdue.edu/~morelanj/RAO/prepare2.html the Pig Latin version you've specified is correct. I've reverted the change and the tests should pass with a correct implementation.
