### ISSUE TITLE
error in config.environment file

### ISSUE THREAD

**Issue by joanrig** [learn-co-curriculum/sinatra-mvc-lab#31]
tests would not run - got a 'require_all' error - even after re-running bundle install and manually installing require_all ... AAQ helped me make this change in line 7

new line 7:
`require_relative '../models/piglatinizer.rb'`

old line 7:
`require_all '/models'`

**Comment by Sdcrouse** [comment]
I think this has been fixed. Line 7 now reads `require_all 'models'`. The tests are running for me.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
