### ISSUE TITLE
No clear accepted rules for pig latin.

### ISSUE THREAD

**Issue by ycohn** [learn-co-curriculum/sinatra-mvc-lab#4]
The tests assume that the word once should be translated as eOncay, but assuming words starting with vowels get an ay appended to the end, it should be Onceay. I'm not sure we're at the level yet to create different cases based on irregular pronunciation...

**Comment by flats** [comment]
Agreed. This is a result of testing for a vowel at the beginning of a word using the `/[aeiou]/` regex and testing for the first consonant sequence using `/[^aeiou]+/`. This obviously does not take capital letters into account.

I think that it would help to have an agreed upon pig latin standard laid out in this lab's README.md. For example, the [Wikipedia entry on Pig Latin](https://en.wikipedia.org/wiki/Pig_Latin#Rules) proposes different rules for words starting with a vowel than are followed in test.

**Comment by AnnJohn** [comment]
Thanks for raising the issue. Will fix this soon.

**Comment by victhevenot** [comment]
assigning to @AnnJohn for pig latin rules

**Comment by genericlady** [comment]
i submitted a pull request i can update the specs it's cool.  Just confirm which style you like in the issue i raised.

**Comment by AnnJohn** [comment]
merged PR that addresses rules for pig latin.
