### ISSUE TITLE
Line 58 of mvc_lab_spec test is slightly wrong

### ISSUE THREAD

**Issue by dannyd4315** [learn-co-curriculum/sinatra-mvc-lab#9]
The word Stream should be returned as reamStay

As I understand Pig Latin - 
If a word starts with two consonants move the two consonants to the end of the word and add "ay."
Example: Child = Ildch + ay = Ildchay

It may be worth adding a note at the bottom of the lesson to show what rules are being adhered to, as I had not used/heard of it before and there are a lot of rules out there.

**Comment by AnnJohn** [comment]
Thanks @dannyd4315 we know that not clarifying pig latin rules is a problem here. We'll fix this as soon as we can.

**Comment by AnnJohn** [comment]
@ruchiramani also for this one too can you see if the issue can be closed because of the PR you merged on pig latin rules yesterday?

**Comment by ruchiramani** [comment]
@AnnJohn `Stream` in pig latin would be `Eamstray`. The current tests reflect this. https://github.com/learn-co-curriculum/sinatra-mvc-lab/blob/master/spec/sinatra_mvc_lab_spec.rb#L58
